### PR TITLE
Add support for dependabot

### PR DESCRIPTION
**Pull request by gaby**
* Support for tracking `gomod` updates.
* Support for tracking `github-actions` updates.

### CODE REVIEW

**Comment by gaby** [comment]
@hellt This should help automate some of the maintenance tasks.

**Comment by hellt** [comment]
Hi @gaby 
I am hesitating...
Although keeping up-to-date deps is generally good, the amount of deps we have is considerable. Having critical deps on something like `docker` may lead to undesired bumps where the client gets updated to a version that requires a newer docker installation, and our testing pipeline may miss this...

Nevertheless, I am curious to try it out, but I would like to ask you to change the checking interval to weekly instead of daily

**Comment by gaby** [comment]
@hellt Changes made. By default dependabot only tracks, and auto-creates a PR for each new update. It does not auto-merge, or auto change your git repo. It still requires the PR to run it's and get accepted by someone.

**Comment by hellt** [comment]
Yes, sure. Let's experiment

**Comment by gaby** [comment]
Awesome! It already created quite a few PR's and is running tests for each one :-)

**Pull request merged**
