### PR TITLE
Return of the Ignite runtime

### PR DESCRIPTION
**Pull request by networkop**
Heya 👋 ,
I've found an easy way to fix the ignite incompatibility with newer versions of k8s.io/apimachinery. It's a one-liner change in the weaveworks/libgitops package:
https://github.com/weaveworks/libgitops/compare/master...networkop:libgitops:patch
With this change, users can once again use ignite to run firecracker microVMs, so it addresses the issues raised in #1036 , #1039 and #1037. 

Sadly, it looks like ignite/libgitops are low on weavework's priority list, so for now the solution involves the use of a fork that I'll maintain.

Additionally, this PR includes an integration test to catch future potential issues with the ignite runtime as they appear.

### CODE REVIEW

**Comment by networkop** [comment]
ignite tests seems to be passing on my laptop. any chance I can have a look at the logs?
```
./tests/rf-run.sh ignite ./tests/05-ignite
==============================================================================
05-Ignite
==============================================================================
05-Ignite.05-Two-Cvx
==============================================================================
Deploy 05-ignite lab                                                  | PASS |
------------------------------------------------------------------------------
Ensure sw1 is reachable over ssh                                      | PASS |
------------------------------------------------------------------------------
Ensure sw2 is reachable over ssh                                      | PASS |
------------------------------------------------------------------------------
05-Ignite.05-Two-Cvx                                                  | PASS |
3 tests, 3 passed, 0 failed
==============================================================================
05-Ignite                                                             | PASS |
3 tests, 3 passed, 0 failed
==============================================================================
Output:  /home/null/containerlab/tests/out/05-ignite-ignite-out.xml
Log:     /home/null/containerlab/tests/out/05-ignite-ignite-log.html
```

**Comment by networkop** [comment]
hm... looks like GH actions don't support /dev/kvm https://github.com/actions/runner-images/issues/183
removing integration tests :(

**Comment by hellt** [comment]
thanks @networkop 
this is excellent news! Would you be willing also removing this block from the docs to reflect the change?

https://github.com/srl-labs/containerlab/blob/main/docs/manual/kinds/cvx.md?plain=1#L21-L22

**Comment by networkop** [comment]
just done that @hellt . I've left a warning only for specific clab releases.

**Comment by hellt** [comment]
cheers, thanks for that fix!

**Pull request merged**
