### PR TITLE
Add auto-remove=yes option to avoid auto-restart policy and cleanup containers automatically

### PR DESCRIPTION
**Pull request by jbemmel**
See https://github.com/srl-labs/containerlab/issues/1055

### CODE REVIEW

**Comment by hellt** [comment]
thanks @jbemmel 
let's name it `restart-policy` to align with the terms docker/k8s use for containers https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy

**Comment by hellt** [comment]
thanks @jbemmel 
I have changed the type to bool as this seems to be inline with the flag value of the docker CLI
Will add a test and merge this

**Comment by jbemmel** [comment]
> thanks @jbemmel
> I have changed the type to bool as this seems to be inline with the flag value of the docker CLI
> Will add a test and merge this

I started with a bool, but the problem is that if you set it to ‘false’ the logic drops down to the next level. A bool cannot distinguish between “not set” and “set to false”

**Comment by hellt** [comment]
@jbemmel yes, initially I decided to not cater for the use case where a true set on kind level can be overridden by `false` set on node level, but it makes sense to do it right from the get go

this PR uses pointers to address that https://github.com/srl-labs/containerlab/pull/1065
anyhow, in the today's release 0.32.2 you should be able to start using this feature with a caveat you know about

**Pull request merged**
