### PR TITLE
ixia-c-one support

### PR DESCRIPTION
**Pull request by hellt**
This is a copy of #817 as I had problems updating the original PR

### CODE REVIEW

**Comment by hellt** [comment]
closing because of a git history issues...

**Comment by hellt** [comment]
@rudranil-das 
the git history got seriously messed up in this PR =) you see how this PR changed commit hashes from the PRs which were not part of ixiac changes. 

I would like to ask you to open a new one with sqashed commits if possible so that only ixia-c relevant changes would be there

**Comment by ashutshkumr** [comment]
@hellt sure, we'll get back a cleaner PR.

**Comment by rudranil-das** [comment]
@hellt created new [PR](https://github.com/srl-labs/containerlab/pull/852)

**Comment by rudranil-das** [comment]
@hellt keeping a [reference](https://github.com/srl-labs/containerlab/pull/817#issuecomment-1090476096) for TBDs from your side for doc changes

**Pull request merged**
