### PR TITLE
Introduce DNS options

### PR DESCRIPTION
**Pull request by steiler**
implementing #453

Doc and Schema adjustments are still missing.

### CODE REVIEW

**Comment by steiler** [comment]
@hellt do you mind taking over the doc and schema part?!

**Comment by hellt** [comment]
@steiler thanks
I have done some renaming, and added docs/schema
I think what is needed is a test in the 01-smoke suite to check that it works

**Comment by steiler** [comment]
Alright @hellt, take a look at the tests.

**Comment by hellt** [comment]
Thanks @steiler 
LGTM

**Pull request merged**
