### PR TITLE
introduce CertificateAuthority and CertificateStore

### PR DESCRIPTION
**Pull request by steiler**
This PR introduces two interfaces and a single respective implementation.
- CertificateAuthority
- CertificateStore

Certificates will for now be created for all of the referenced nodes for a topology. This is meant to change once the KindProperties (#1207) are available. Then it will be again restricted to SRL nodes.
As a next step also the introduction of a seperate config knob is planned to enable cert creation for individual nodes.

### CODE REVIEW

**Comment by steiler** [comment]
Introducign the config knob will solve this issue #1211

**Comment by steiler** [comment]
This PR will allow an easy implementation of #746 since we have proper interfaces, which the new implementation simply needs to satisfy.

**Comment by steiler** [comment]
We should maybe consider pushing the certificate mangement and creation down to the node instead of trying to manage this centrally. This would provide the nodes with the ability to e.g. delay cert creation, to then request the cert also with the mgmt IP as a SAN value #150

**Review by hellt — APPROVED** [review]

**Comment by steiler** [comment]
looking good

**Pull request merged**
