### PR TITLE
Introducing NodeRegistry

### PR DESCRIPTION
**Pull request by steiler**
The Implementation, using the once construct is ugly and not quite good practice. Also the global var we used as a node registry is non-optimal.
Here is a different approach introducing a NodeRegistry. A seperate object that keeps track of the registered Node types.

### CODE REVIEW

**Comment by hellt** [comment]
Hi @steiler 
I have removed what I consider to be unnecessary interfaces. What was the point of adding them?
The rest looks good to me. If you are ok with removed interfaces and me moving the registry to the Clab struct I am good with merging this

**Comment by steiler** [comment]
I like to use interfaces in a lot more places that we use them right now.
interfaces is not just a vehicle to implement different production level behaviours but also helps a lot with testing.
You can generate mocks only from interfaces afaikt and use these to ease testing.
Sure this was not in use just now... but in my view a good practice.

**Comment by hellt** [comment]
I think creating the interface is only viable when you have multiple types conforming to it. Like different nodes and the corresponding node interface. 
An interface that is implemented by a single type doesn't bring any benefit imho (and complicates code by introducing another level of indirection). You still can create a struct  used for testing manually and perform the tests over it -- especially in case of simple structs like registry and credentials

**Comment by steiler** [comment]
It would be used to mock the registry itself not for testing the registry.

**Pull request merged**
