### PR TITLE
Allow combination of filter and topology in exec command

### LINKED ISSUE #1728: exec with --label constraint runs on all topologies
I have several lab topologies running on my clab host, I am specifying a particular topology file and selecting the SRL nodes with the `--label`, however exec is running the command on all SRL nodes in all running topologies

```
╭─drelliot@snoopy ~/git/dhcpv6/lab ‹init●› 
╰─$ sudo clab version
  ____ ___  _   _ _____  _    ___ _   _ _____ ____  _       _     
 / ___/ _ \| \ | |_   _|/ \  |_ _| \ | | ____|  _ \| | __ _| |__  
| |  | | | |  \| | | | / _ \  | ||  \| |  _| | |_) | |/ _` | '_ \ 
| |__| |_| | |\  | | |/ ___ \ | || |\  | |___|  _ <| | (_| | |_) |
 \____\___/|_| \_| |_/_/   \_\___|_| \_|_____|_| \_\_|\__,_|_.__/ 

    version: 0.48.1
     commit: 2184f2df
       date: 2023-11-13T18:02:22Z
     source: https://github.com/srl-labs/containerlab
 rel. notes: https://containerlab.dev/rn/0.48/#0481

╭─drelliot@snoopy ~/git/dhcpv6/lab ‹init●› 
╰─$ sudo clab exec -t dev.clab.yml --label clab-node-kind=srl --cmd 'sr_cli "tools system app-management application app_mgr reload"'  
INFO[0000] Parsing & checking topology file: dev.clab.yml 
INFO[0004] Executed command "sr_cli tools system app-management application app_mgr reload" on the node "clab-dhcpv6-dev-srl1". stdout: 
INFO[0004] Executed command "sr_cli tools system app-management application app_mgr reload" on the node "clab-rad-srl". stdout: 
INFO[0004] Executed command "sr_cli tools system app-management application app_mgr reload" on the node "clab-ansible-srl21". stdout: 
INFO[0004] Executed command "sr_cli tools system app-management application app_mgr reload" on the node "clab-ansible-srl12". stdout: 
INFO[0004] Executed command "sr_cli tools system app-management application app_mgr reload" on the node "clab-ansible-srl11". stdout: 
INFO[0004] Executed command "sr_cli tools system app-management application app_mgr reload" on the node "clab-ansible-srl22". stdout: 
╭─drelliot@snoopy ~/git/mso-dhcpv6-relay-agent/lab ‹init●› 
╰─$
```

### PR DESCRIPTION
**Pull request by steiler**
close #1728

### CODE REVIEW

**Comment by steiler** [comment]
We should maybe error out if neither topofile nor labels are provided?!

**Comment by steiler** [comment]
mava@server01:~/projects/containerlab3$ sudo bin/containerlab exec --label clab-node-name\=ext1 --cmd "ip link show dev eth1"
Error: none or more than one topology files found, can't auto select one

the issue with the ext containers is, that we are always trying to load a topo file...

**Comment by hellt** [comment]
I wonder if we should rather ditch `topo` from this command at all.
Can't we just rely on node labels to invoke commands?

**Comment by steiler** [comment]
To me the remark here #1728  was quite valid, handing in a topology file and a label for a certain kind shold limit to nodes within the topo that have a certain kind ...
But it seems with all the automagic we build around this kind of combination ext container and label selection is non-trivial.

**Comment by steiler** [comment]
One could argue that external containers should proabably be handled outside of clab ... and we declare this now a nono use-case

**Comment by hellt** [comment]
@steiler but don't we have enough label to select both the topology name and node kind name?

What I am thinking about is

```
exec --label clab-topo-name=foo --label clab-kind-name=bar
```

to basically rely on labels to filter out the container to run exec on.

Maybe for ext-containers this is more difficult as they might not even be tagged unless we load the topology and read those fake nodes into the nodes list

**Comment by hellt** [comment]
I unblocked this PR, and made it to work with and without a topo file, which unblocked ext-container tests.

**Pull request merged**
