### PR TITLE
json output for `exec` command

### PR DESCRIPTION
**Pull request by steiler**
./containerlab exec -t lab-examples/clos02/clos02.clab.yml -j sr_cli "show interface mgmt0 brief | as json"

will provide. This is with no label selector applied, Hence you will get errors with the client containers.

Shall we also add the return code? in view that might also make sense. 

```
root@ubuntu:/home/ubuntu/containerlab# ./containerlab exec -t lab-examples/clos02/clos02.clab.yml -j sr_cli "show interface mgmt0 brief | as json" | jq
{
  "/clab-clos02-client1": {
    "stderr": "",
    "stdout": "OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: \"sr_cli\": executable file not found in $PATH: unknown\r\n"
  },
  "/clab-clos02-client2": {
    "stderr": "",
    "stdout": "OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: \"sr_cli\": executable file not found in $PATH: unknown\r\n"
  },
  "/clab-clos02-client3": {
    "stderr": "",
    "stdout": "OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: \"sr_cli\": executable file not found in $PATH: unknown\r\n"
  },
  "/clab-clos02-client4": {
    "stderr": "",
    "stdout": "OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: \"sr_cli\": executable file not found in $PATH: unknown\r\n"
  },
  "/clab-clos02-leaf1": {
    "stderr": "",
    "stdout": {
      "IfBrief": [
        {
          "Admin State": "enable",
          "Oper State": "up",
          "Port": "mgmt0",
          "Speed": "1G"
        }
      ]
    }
  },
  "/clab-clos02-leaf2": {
    "stderr": "",
    "stdout": {
      "IfBrief": [
        {
          "Admin State": "enable",
          "Oper State": "up",
          "Port": "mgmt0",
          "Speed": "1G"
        }
      ]
    }
  },
  "/clab-clos02-leaf3": {
    "stderr": "",
    "stdout": {
      "IfBrief": [
        {
          "Admin State": "enable",
          "Oper State": "up",
          "Port": "mgmt0",
          "Speed": "1G"
        }
      ]
    }
  },
  "/clab-clos02-leaf4": {
    "stderr": "",
    "stdout": {
      "IfBrief": [
        {
          "Admin State": "enable",
          "Oper State": "up",
          "Port": "mgmt0",
          "Speed": "1G"
        }
      ]
    }
  },
  "/clab-clos02-spine1": {
    "stderr": "",
    "stdout": {
      "IfBrief": [
        {
          "Admin State": "enable",
          "Oper State": "up",
          "Port": "mgmt0",
          "Speed": "1G"
        }
      ]
    }
  },
  "/clab-clos02-spine2": {
    "stderr": "",
    "stdout": {
      "IfBrief": [
        {
          "Admin State": "enable",
          "Oper State": "up",
          "Port": "mgmt0",
          "Speed": "1G"
        }
      ]
    }
  },
  "/clab-clos02-spine3": {
    "stderr": "",
    "stdout": {
      "IfBrief": [
        {
          "Admin State": "enable",
          "Oper State": "up",
          "Port": "mgmt0",
          "Speed": "1G"
        }
      ]
    }
  },
  "/clab-clos02-spine4": {
    "stderr": "",
    "stdout": {
      "IfBrief": [
        {
          "Admin State": "enable",
          "Oper State": "up",
          "Port": "mgmt0",
          "Speed": "1G"
        }
      ]
    }
  },
  "/clab-clos02-superspine1": {
    "stderr": "",
    "stdout": {
      "IfBrief": [
        {
          "Admin State": "enable",
          "Oper State": "up",
          "Port": "mgmt0",
          "Speed": "1G"
        }
      ]
    }
  },
  "/clab-clos02-superspine2": {
    "stderr": "",
    "stdout": {
      "IfBrief": [
        {
          "Admin State": "enable",
          "Oper State": "up",
          "Port": "mgmt0",
          "Speed": "1G"
        }
      ]
    }
  }
}
```

### CODE REVIEW

**Comment by steiler** [comment]
implementation of #463.
If the returned string can not be parsed as json, it is returned as a string field.
just stdout is tried to parse, stderr is always a string field. 

Do we need a specific field indicating of under stdout we have a string or a json struct?

**Comment by hellt** [comment]
I think it is better to keep consistency with the inspect command where we
have a flag `--format | -f` that takes a string value of either `table` or
`json`

**Comment by steiler** [comment]
@hellt changed it to -f / --format [plain, json]

**Comment by hellt** [comment]
I think it is safe to rebase this request on top of #469 to incorporate the changes Karim made

**Comment by hellt** [comment]
I've made a `--cmd` flag to be in line with all the rest of commands, and merged the current master
also added a doc entry

it looks ok to me at this moment, @steiler you can check this and if it is all ok, feel free to merge

**Pull request merged**
