### PR TITLE
populate bridgeName if inspect cmd is run with --all or --name

### PR DESCRIPTION
**Pull request by karimra**
#432

### CODE REVIEW

**Comment by steiler** [comment]
Karim did you consider the network mode "host"?
Quickly scanning the code I unfortunately can't tell.
https://github.com/srl-labs/containerlab/blob/62e901c512cc4f8bd54d509065c3fb7ef2b1e8dd/runtime/docker/docker.go#L222-L236

**Comment by karimra** [comment]
what would be printed in case of host mode ?

**Comment by hellt** [comment]
I think for now it is ok if it prints nothing (output from the tip of this branch)

image

the potential improvements are to print `host` maybe?

**Comment by karimra** [comment]
yes, there is basically nothing to print, network name is `host` and was not created by clab --> skip

Instead of writing `host` under an IP address column, maybe add a column `Network Mode` or `Bridge Name`?

**Comment by steiler** [comment]
Printing host sounds good to me.
Noting is also fine for now, just thought that this case might cause errors, not sure if this would be covered by a test so far.

**Comment by steiler** [comment]
@karimra to basically normalize it ... thats also a great idea!

**Comment by hellt** [comment]
I think a column named `Network` with the potential values makes sense, wdyt?

- docker network name if it is a bridged network
- `host-mode` string if it is a host mode networ

**Pull request merged**
