### PR TITLE
Update sonic-vs.md

### PR DESCRIPTION
**Pull request by sc68cal**
Add link to documentation on how to build SONiC docker images

### CODE REVIEW

**Comment by sc68cal** [comment]
I'll be working through this next week, so leaving as a draft for now

**Comment by hellt** [comment]
Hi @sc68cal 
do you plan to continue this one? Or should I take this as it is now?

**Comment by sc68cal** [comment]
Oh. Yeah looks like this is good to go. Sorry, I made this a draft because I think I was not 100% certain that the syntax was right.

**Comment by sc68cal** [comment]
I also _tried_ to build the SONiC docker image and to be honest it just filled up my VM's disk space and failed. It looks like it's a very difficult thing to build. I gave up after a couple tries.

**Comment by hellt** [comment]
I have the following build instructions which seemed to work ~6 months ago
Haven't tried this myself, but maybe you want to give it a try, dunno

```
SONiC Build Process

 

Build from scratch steps for docker-vs.

 

Easiest method is to use Ubuntu-server-16.04 VM right now.  This will produce a docker-vs image that can be used for testing purposes.  Can use any hypervisor, however vmx flags (for kvm) must be available (VT-d).

 

Hyper-V / Virtual Box / Parallels / KVM / etc should all work. 

 

Current System

 

Windows Hyper-V Gen 2

Ubuntu 16.04 VM

4 vCPU - i7-9700k (110W max TDP limit imposed) (also tested 7 cores – minor improvement)

6144MB RAM (also tested 8192MB)

220GB SATA SSD (anything under ~160GB will likely fail)

300-400 Mbps speed over WiFi to Internet (to note for timing speeds listed below)

 

Note: Disk IO seems to effect speed of the build.  If possible, use SSD/NVMe backed drives.

 

 

Following Steps from the build guide here:

 

https://github.com/Azure/sonic-buildimage

 

 

Setup Pre-reqs

 

Install docker

 

Steps taken from here: https://docs.docker.com/engine/install/ubuntu/

 

sudo apt-get update

sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

sudo apt-get update

sudo apt-get install docker-ce docker-ce-cli containerd.io

sudo usermod -aG docker $USER

sudo systemctl enable docker

sudo systemctl start docker

 

logout / login to pickup docker user change

 

Validate docker

 

docker run hello-world

 

Install SONiC requirements

 

sudo apt-get install -y python-pip

sudo python2 -m pip install -U pip==9.0.3

sudo pip install --force-reinstall --upgrade jinja2>=2.10

sudo pip install j2cli

 

 

Build Steps

 

First time builds will take longer.

 

git clone https://github.com/Azure/sonic-buildimage.git

 

cd sonic-buildimage

 

EDIT rules/config

# Modify Build Jobs to match vCPU

SONIC_CONFIG_BUILD_JOBS = 4

DEFAULT_PASSWORD = admin

SHUTDOWN_BGP_ON_START = n

 

sed -i 's/SONIC_CONFIG_BUILD_JOBS = 1/SONIC_CONFIG_BUILD_JOBS = 4/g' rules/config

sed -i 's/DEFAULT_PASSWORD = YourPaSsWoRd/DEFAULT_PASSWORD = admin/g' rules/config

sed -i 's/# SHUTDOWN_BGP_ON_START = y/SHUTDOWN_BGP_ON_START = n/g' rules/config

 

make init

make configure PLATFORM=vs

make target/docker-sonic-vs.gz

 

Rough Timing Notes (as per my setup):

make init: 90 seconds

make configure:  - 10 - 15 minutes

make target: 40 - 60 minutes depending on vCPU/HDD type (I tested both SATA SSD and NVMe)

 

Testing the Build

 

Docker image is available at 

 

target/docker-vs.gz

 

Load docker image

 

docker load < docker-sonic-vs.gz
```

**Comment by sc68cal** [comment]
> (anything under ~160GB will likely fail)

I'll check the VM that I built but 160GB might have been what I allocated. So I would not be surprised that it failed. I remember starting at like 80GB and slowly bumping it and re-trying, and failing. I think the limiting factor was the PC I was running the VM on didn't have a lot of free space.

**Comment by hellt** [comment]
I will take this in, and if you happen to check the process I shared, feel free to raise a new one
thanks!

**Comment by antongisli** [comment]
trying to build this using these instructions - also noticed it is very finicky. Did the 16.04 have great significance to success?
My colleagues and I also noticed better lucking using their 202106 branch.

**Comment by hellt** [comment]
maybe augmenting this instructions with some steps from the official guide will make it more streamlined? https://github.com/Azure/sonic-buildimage/blob/master/README.md

**Comment by antongisli** [comment]
I built it successfully from master tonight. I used a fresh install of Ubuntu server 20.04, and followed the instructions from https://github.com/Azure/sonic-buildimage/blob/master/README.md - except I followed your guide above to build the docker target:

`sed -i 's/SONIC_CONFIG_BUILD_JOBS = 1/SONIC_CONFIG_BUILD_JOBS = 4/g' rules/config

sed -i 's/DEFAULT_PASSWORD = YourPaSsWoRd/DEFAULT_PASSWORD = admin/g' rules/config

sed -i 's/# SHUTDOWN_BGP_ON_START = y/SHUTDOWN_BGP_ON_START = n/g' rules/config

make init

make configure PLATFORM=vs

make target/docker-sonic-vs.gz`

In case it's helpful for anybody else:

I discovered the location to download the artifacts from the automated build jobs, by looking at their [google group](https://groups.google.com/g/sonicproject/?pli=1).

Build artifacts are [here](https://sonic-build.azurewebsites.net/ui/sonic/pipelines/142/builds?branchName=master). Go to "build history" -> artifacts -> keep clicking and eventually you can see the target folder which you can download.

**Comment by antongisli** [comment]
I created this to make life easier for everyone .. https://github.com/antongisli/sonic-builder

**Comment by hellt** [comment]
wow, thanks @antongisli!
do you mind pushing the recent sonic-vs you build to some registry so others can try it out? Or maybe just do it adhoc via ttl.sh and I will push it to srl-labs registry.

I am also curious if one can use GH actions VM to build sonic. they don't have 16GB ram, but maybe worth trying...

**Comment by antongisli** [comment]
Can definitely do it adhoc. Curious about the REST API setting for SONiC - do you know if gNMI is available without that option being enabled? 

I wanted to play with tools that would connect to SONiC for config management (which is why I've been doing this). Do you or anybody else know? The one I've managed to build so far did not have that REST API config knob enabled (will try to enable it and see if it will still build).

**Comment by hellt** [comment]
I haven't tried gnmi on sonic. By all means I try to avoid touching it :D

**Comment by antongisli** [comment]
fair enough :) I think that my repo is fairly "reliable now" for building, maybe you want to mention it somewhere in the sonic docs for containerlab? Others I think will find it useful.

**Comment by hellt** [comment]
@antongisli  added ref to your repo in aa749c07

**Comment by antongisli** [comment]
@hellt - who out of anyone you know has run the sonic vs docker image and actually had a working lab? 
None of the artifacts work that I have created, or downloaded from the sonic team. if you know someone that actually had this working and functioning in a containerlab, please point me at them  in case I've done something stupid when running the images. I wrote about  my struggles here:

https://groups.google.com/u/1/g/sonicproject/c/-vIipAPlHLA

**Comment by hellt** [comment]
@antongisli pick one from here

```
docker pull ghcr.io/hellt/sonic-vs:2020-11-12
```

**Comment by antongisli** [comment]
this one actually looks sane and works. I hadn't tried 2020-11-12. I'm going to check the ones from official artifacts and report back. Thx.

**Comment by sc68cal** [comment]
We might want to add a link to to https://sonic-build.azurewebsites.net/ui/sonic/pipelines - which is a link shared on the SONiC mailing list for where build artifacts are being saved

**Comment by hellt** [comment]
@sc68cal do you know how one can get the artifacts from there? I couldn't find any container images archives

**Comment by antongisli** [comment]
Click build history -> artifacts -> click the link (should be only one) ->
scroll down until you find the docker image, and then you can grab a static
link or download it.

**Comment by hellt** [comment]
@antongisli like this one?

image

have you been able to use that docker images within containerlab?

**Comment by antongisli** [comment]
yes, like that one. No, they don't work however I suspect there is a
difference in versions. Try one built from 202011 or earlier  (I've been
sick at home with kids so have not managed to get around to it yet).

there is also this thread I started on the sonic mailing list:
https://groups.google.com/g/sonicproject/c/-vIipAPlHLA/m/tN00bHRmDQAJ

Somehow it seems that in order for the docker image to work, it needs to be
married to a "base image" that provides the networking setup. I don't know
if this is a new behaviour or not.

**Comment by hellt** [comment]
@antongisli yes, that "mating" with base image is something that official sonic docs mentioned back then when I did the initial integration
https://github.com/Azure/sonic-buildimage/blob/master/platform/vs/README.vsdocker.md
but it is not needed, since I do the same kind of stuff in the background with containerlab.

So I think your issue with container being rendered unusable is with something else. It is funny no one can get a simple docker based instructions for some artifact that is available currently.

**Comment by antongisli** [comment]
I think it was a red herring now.

I took an image that I built, and I've gotten it pinging between an SRlinux
container and a sonic docker image - as you said, you are doing the veth
plumbing behind the scenes so I thought maybe it will work.

The red herring comes from lots of things being broken/not added into the
sonic docker image, it doesn't appear to be meant for this kind of usage -
rather used for some internal testing that they do. Seems hobbled, with
lots of commands with empty output.

It also, annoyingly, sets the interface names randomly to Ethernet0,
Ethernet4, Ethernet8 etc. I tried to change it to Ethernet4, but it didn't
work without intervention: SONIC CLI commands couldn't plumb the interface,
but I could do it with ifconfig/ip addr add commands, and at that point I
could ping the SR linux box.

***@***.***:/# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group
default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: Ethernet24: <BROADCAST,MULTICAST> mtu 9100 qdisc noop state DOWN group
default qlen 1000
    link/ether 02:42:ac:14:14:02 brd ff:ff:ff:ff:ff:ff
3: Ethernet28: <BROADCAST,MULTICAST> mtu 9100 qdisc noop state DOWN group
default qlen 1000
    link/ether 02:42:ac:14:14:02 brd ff:ff:ff:ff:ff:ff
4: Ethernet36: <BROADCAST,MULTICAST> mtu 9100 qdisc noop state DOWN group
default qlen 1000
    link/ether 02:42:ac:14:14:02 brd ff:ff:ff:ff:ff:ff
5: Ethernet32: <BROADCAST,MULTICAST> mtu 9100 qdisc noop state DOWN group
default qlen 1000
    link/ether 02:42:ac:14:14:02 brd ff:ff:ff:ff:ff:ff
6: Ethernet40: <BROADCAST,MULTICAST> mtu 9100 qdisc noop state DOWN group
default qlen 1000
    link/ether 02:42:ac:14:14:02 brd ff:ff:ff:ff:ff:ff
7: Ethernet44: <BROADCAST,MULTICAST> mtu 9100 qdisc noop state DOWN group
default qlen 1000
    link/ether 02:42:ac:14:14:02 brd ff:ff:ff:ff:ff:ff
8: Ethernet0: <BROADCAST,MULTICAST> mtu 9100 qdisc noop state DOWN group
default qlen 1000
    link/ether 02:42:ac:14:14:02 brd ff:ff:ff:ff:ff:ff
9: Bridge: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 9100 qdisc noqueue state
DOWN group default qlen 1000
    link/ether 02:42:ac:14:14:02 brd ff:ff:ff:ff:ff:ff
10: dummy: <BROADCAST,NOARP> mtu 1500 qdisc noop master Bridge state DOWN
group default qlen 1000
    link/ether e2:c7:d9:2d:9f:84 brd ff:ff:ff:ff:ff:ff
100: ***@***.***: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue
state UP group default
    link/ether 02:42:ac:14:14:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.20.20.2/24 brd 172.20.20.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2001:172:20:20::2/64 scope global nodad
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe14:1402/64 scope link
       valid_lft forever preferred_lft forever
104: ***@***.***: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9500 qdisc
noqueue state UP group default
    link/ether aa:c1:ab:fe:dd:4f brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet 192.168.1.2/24 scope global Ethernet4
       valid_lft forever preferred_lft forever

How do you configure eth0 Roman?

Regards,
Anton

**Comment by hellt** [comment]
> How do you configure eth0 Roman?
the eth0 is the first front panel port, iirc

here is how I did that a long time ago https://containerlab.srlinux.dev/lab-examples/srl-sonic/

**Comment by antongisli** [comment]
Actually I'm wondering how containerlab has configured the  management
interface, since I have not done that myself. Somehow containerlab must be
setting some configuration, and that works (can ping the IP from the
management network). I'm getting close to giving up on docker sonic, and
think I'll just resort to vmnetlab.

**Comment by hellt** [comment]
the management interface config is handled by the docker itself.
like for a regular container, docker will setup the `eth0` interface inside the container namespace and configure it with an address from the docker network range

**Comment by hellt** [comment]
for vrnetlab we would still need to create a flavor in vrnetlab project to handle sonic img
it is trivial, but hasn't been done yet

**Comment by antongisli** [comment]
ok. not too sure what that means. should I create an issue for it?

**Comment by hellt** [comment]
you can create one, sure.

**Comment by ckuhtz** [comment]
I understand this is closed and merged.  Wanted to drop this reference here to the unofficial repo for the SONiC images that are coming out of the build pipeline:
https://sonic.software/
I think the docker-sonic-vs.gz image is what you want, trying to get that to work now. I had zero luck with the build scripts in arriving at anything resembling a working image.

**Comment by hellt** [comment]
Yeah, thanks @ckuhtz 
We are using containers from this site. Maybe you want to update the docs with a reference to it? Would help others who don't know about it

**Comment by ckuhtz** [comment]
@hellt when you're saying "are using containers from this site", is that described anywhere how that's done?  Things like https://github.com/srl-labs/containerlab/blob/main/lab-examples/sonic01/sonic01.clab.yml still specify the 2020 image

**Comment by hellt** [comment]
We just use it in the labs, but indeed the example should be updated as well.

**Comment by hellt** [comment]
You download the tar.xz file form sonic software and do "docker load -i (file)" to get the image in the local store

**Pull request merged**
