### PR TITLE
Fix reconfigure on removed nodes

### PR DESCRIPTION
**Pull request by steiler**

### CODE REVIEW

**Comment by hellt** [comment]
@steiler when you remove the container it is not longer present at all. The #1444 has a different scenario, a container is present, but in an existed state.
Can this be reproduced?

**Comment by steiler** [comment]
no in that way I still can't reproduce.

**Comment by kellerza** [comment]
What I do see that is that when you build a new lab and add a new node to the topo file, `--reconfigure` does not work

```bash
❯ clab deploy --reconfigure                               
INFO[0000] Containerlab v0.41.1 started
INFO[0000] Parsing & checking topology file: epe.clab.yaml
INFO[0000] Removing /home/kellerza/ip-lab/clab/sr-os/bgp-epe/clab-epe directory...
Error: containers ["clab-epe-ni1" "clab-epe-ni2" "clab-epe-oti1" "clab-epe-oti2" "clab-epe-otibgp"] already exist. Add '--reconfigure' flag to the deploy command to first remove the containers and then deploy the lab
```

**Comment by steiler** [comment]
This became part of #1475

**Pull request closed without merging**
