### PR TITLE
support for external containers in `network-mode`

### PR DESCRIPTION
**Pull request by hellt**
supersedes #966

Hi @steiler 

what do you think about this approach, where a single `container:<cont-name>` instruction is used both for clab and non-clab managed containers.

Mainly I didn't want to introduce another string-based config param (external-container), and proposing to use a single `container:<cont-name>` instead, as it makes (I hope) things simplier for users.

One thing I changed here is the way we use container ID in filter string, before it was just `cID`, but Docker does not use exact matches for that value, instead it uses substring matches. To fix that I used a regexp-based string value to make sure that when we use `GetContainer` we are able to have exact match by the provided name

### CODE REVIEW

**Comment by LimeHat** [comment]
@hellt what would happen if a user has a container named "lab-1" in a clab topology & as an external entity at the same time?
It seems that the latter will take precedence, but this might not be intended or desired?

**Comment by hellt** [comment]
@LimeHat good call. I have changed the logic to check for internal containers first.
the mandatory prereq for making clab-scheduled container to be picked up is to use a startup-delay for a donor container, e.g.

```yaml
topology:
  nodes:
    donor:
      kind: linux
      image: alpine:3
    node1:
      kind: linux
      network-mode: container:donor
      startup-delay: 2
      image: alpine:3
```

as otherwise donor might not have enough time to deploy

**Comment by steiler** [comment]
What if we would provide, as a pre-step to any deploy action some struct to the runtime, that it knows which containers are part of the topology. This struct also holds a status, which is managed by the runtime itself. And it could go and do dependency checking itself, start the container when all the internal dependencies are finally started and therby you'd get rid of the sleep timer / start delay foo.
first thought about injecting that list into the container start, but there we are too deep already in the deployment of just a single container, but finally pushing that into the runtime seems to even make more sense to me.
Thought?

**Comment by hellt** [comment]
@steiler I like the idea, and had a thought about it when looking at this PR. But I am not so sure it is runtime business.
I think maybe it is better to look at scheduling function that we have rudimentary support for.

For instance, right now we have two queues - static IP and dynamic IP nodes which are scheduled one after another to guarantee, that nodes with static IPs are created first, and then dyn IP nodes go in.

https://github.com/srl-labs/containerlab/blob/main/clab/clab.go#L165-L192

and it looks like it would be great to have a more feature rich scheduler package that will take care of all the dependencies. Maybe even creating a graph of nodes that we can use for deployments...


But we got carried away here :D
@steiler If you don't have objections to this current impl, I am willing to merge it and carve out a release.

**Comment by steiler** [comment]
Interesting, first time I hear of that scheduler.
Yes, it sounds like it belongs even there.

Anyways this PR seems fine so far.

**Pull request merged**
