### PR TITLE
Add dark/light mode aware clab favicon

### PR DESCRIPTION
**Pull request by kaelemc**
Nice and simple. Change the favicon to the clab icon, which is aware and changes the outline to black or white depending on the browser theme.

Video is in the discord: https://discord.com/channels/860500297297821756/865526691350839296/1312046431103750207

### CODE REVIEW

**Comment by hellt** [comment]
lovely. works in chrome 
somehow doesn't work in Safari, but current version doesn't show the beaker favicon either.

**Comment by kaelemc** [comment]
@hellt Seems Safari doesn't support the `.svg` favicons, if you can add html tags to the header in mkdocks material I think you can add a fallback png/ico favicon.

**Comment by kaelemc** [comment]
* but it won't be able to change colour of course.

**Comment by hellt** [comment]
yeah, indeed

https://caniuse.com/link-icon-svg

fuck safari then

**Comment by kaelemc** [comment]
LOL... I follow the logic though :)

**Pull request merged**
