### PR TITLE
add fortigate node

### PR DESCRIPTION
**Pull request by robotwalk**

### CODE REVIEW

**Comment by steiler** [comment]
should also contain "fortios" as the kind name.

**Comment by hellt** [comment]
I renamed the kind to `fortinet_forios` to keep it consisten with the naming scheme

you can try the beta build


```
sudo docker run --rm -v $(pwd):/workspace ghcr.io/oras-project/oras:v1.1.0 pull ghcr.io/srl-labs/clab-oci:14aac630
``` 

running this cmd will download the containerlab binary in your PWD

**Comment by steiler** [comment]
> **ADD1** as @steiler found, the registration part is missing -- example https://github.com/srl-labs/containerlab/blob/main/nodes/checkpoint_cloudguard/checkpoint_cloudguard.go#L21

This is where it would need to go. https://github.com/srl-labs/containerlab/blob/main/clab/register.go

**Comment by hellt** [comment]
@robotwalk thanks, I am a bit behind with some other tasks, just pinging you to tell I have not forgotten about this one

**Comment by hellt** [comment]
Hi @robotwalk 
I have tried to launch the image built with https://github.com/hellt/vrnetlab/pull/174 and it boots fine after I did [a8ad97a](https://github.com/srl-labs/containerlab/pull/1917/commits/a8ad97a192193b5bc6126cba63639ab2ed6bf34b)

But, I wonder what should I expect from this basic boot? It seems ssh doesn't respond, but telnet works.

How people usually consume fortios?

**Comment by hellt** [comment]
It's all good. The DHCP assigned address is assigned by qemu so no need for explicit config

**Comment by robotwalk** [comment]
So I just build containerlabs with the current code and ran the lab-examples/fortigate/fortinet.clab.yml topology

```
./bin/containerlab deploy -t lab-examples/fortigate/fortinet.clab.yml
```

Getting healthy
```
docker ps
CONTAINER ID   IMAGE                        COMMAND                  CREATED         STATUS                   PORTS                                                                            NAMES
b716ac700587   vrnetlab/vr-fortios:v7.0.0   "/launch.py --userna…"   2 minutes ago   Up 2 minutes (healthy)   22/tcp, 80/tcp, 443/tcp, 830/tcp, 3443/tcp, 5000/tcp, 10000-10099/tcp, 161/udp   clab-fortigate-forti2
8db36ce45d42   vrnetlab/vr-fortios:v7.0.0   "/launch.py --userna…"   2 minutes ago   Up 2 minutes (healthy)   22/tcp, 80/tcp, 443/tcp, 830/tcp, 3443/tcp, 5000/tcp, 10000-10099/tcp, 161/udp   clab-fortigate-forti1
```

Get ips

```
$ docker ps -q | xargs -n1 docker inspect | grep -i ipaddress
            "SecondaryIPAddresses": null,
            "IPAddress": "",
                    "IPAddress": "172.20.20.2",
            "SecondaryIPAddresses": null,
            "IPAddress": "",
                    "IPAddress": "172.20.20.3",
```

SSH into

```
$ ssh -l admin 172.20.20.2
The authenticity of host '172.20.20.2 (172.20.20.2)' can't be established.
ED25519 key fingerprint is SHA256:+KSIszKGsTyvgqOPU2nxSp/QW4AgRmyOxCabYsrV1Dc.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '172.20.20.2' (ED25519) to the list of known hosts.
admin@172.20.20.2's password:
forti2 #

$ ssh -l admin 172.20.20.3
The authenticity of host '172.20.20.3 (172.20.20.3)' can't be established.
ED25519 key fingerprint is SHA256:0CiIyNO93oVwewQJXdHtyHuNNayXMeR1gpCmWmvLenE.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '172.20.20.3' (ED25519) to the list of known hosts.
admin@172.20.20.3's password:
forti1 #
```

SSH is enabled by default
```
forti2 # show system interface
config system interface
    edit "port1"
        set vdom "root"
        set mode dhcp
        set allowaccess ping https ssh fgfm
        set type physical
        set snmp-index 1
    next
    edit "port2"
        set vdom "root"
        set type physical
        set snmp-index 2
    next
    edit "ssl.root"
        set vdom "root"
        set type tunnel
        set alias "SSL VPN interface"
        set snmp-index 3
    next
    edit "fortilink"
        set vdom "root"
        set fortilink enable
        set ip 10.255.1.1 255.255.255.0
```
The second interface is also there and so is the linkt between the two nodes

image

**Comment by hellt** [comment]
thanks @robotwalk

**Pull request merged**
