### PR TITLE
Check for SSE3 CPU availability

### PR DESCRIPTION
**Pull request by steiler**
Implementing #837
The `NodeConfig` now contains an `SSE3Required bool` flag. 
If SSE3 is required just set this flag to true in the kind `init()`
If a topology is deployed that requires SSE3 it is checked and an exception is thrown if unavailable. If not required by any kind we continue.
Bools are by default initialized with the value false. So this flag needs to only be touched when SSE3 is explicitely required.

### CODE REVIEW

**Comment by hellt** [comment]
What if for NodeConfig struct we create a field `HostRequirements` which will be outlined like this

```go
{
  SSE3 bool
}
```

with an idea that eventually we may populate it with more cpu instruction sets or other host related requirements?

**Comment by hellt** [comment]
Hi @steiler 
in [a5c880c](https://github.com/srl-labs/containerlab/pull/846/commits/a5c880c9ac2e6c44833568fbf95e062985404c99) I added what I was referring to as using a struct for host requirements

Check it out, I think it is quite straightforwards and is inline with what you did initially

**Comment by steiler** [comment]
Yes looking good!
whats your opinion on implementing the `MinCPURequired` and alike in the same way?
That would be uniform and keep all kind related difference as a local definition on the kind.

**Comment by hellt** [comment]
Yes. We will do this in a separate PR

**Pull request merged**
